<?php
/**
 * Dynamic PHP Script Handler for Bhaiyyantop Theme
 *
 * Replaces standalone JS files with PHP functions that generate and output
 * optimized, secure, inline script logic via wp_footer.
 *
 * @package Bhaiyyantop
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

/**
 * Returns inline JavaScript string generated by PHP for general theme interactivity.
 *
 * @return string JavaScript code string.
 */
function bhaiyyantop_get_theme_inline_script() {
    ob_start();
    ?>
    document.addEventListener('DOMContentLoaded', function() {
        'use strict';

        // 1. Breaking News Ticker Auto Scroll
        const tickerList = document.querySelector('.ticker-list');
        const tickerItems = document.querySelectorAll('.ticker-item');
        const prevBtn = document.querySelector('.ticker-prev');
        const nextBtn = document.querySelector('.ticker-next');
        
        if (tickerList && tickerItems.length > 0) {
            let tickerIndex = 0;
            let tickerInterval = null;

            function getTranslateValue() {
                let width = 0;
                for (let i = 0; i < tickerIndex; i++) {
                    width += tickerItems[i].offsetWidth;
                }
                return width;
            }

            function updateTicker() {
                tickerList.style.transform = `translateX(-${getTranslateValue()}px)`;
            }

            function slideNext() {
                tickerIndex++;
                if (tickerIndex >= tickerItems.length) {
                    tickerIndex = 0;
                }
                updateTicker();
            }

            function slidePrev() {
                tickerIndex--;
                if (tickerIndex < 0) {
                    tickerIndex = tickerItems.length - 1;
                }
                updateTicker();
            }

            function startTicker() {
                if (!tickerInterval) {
                    tickerInterval = setInterval(slideNext, 4000);
                }
            }

            function stopTicker() {
                if (tickerInterval) {
                    clearInterval(tickerInterval);
                    tickerInterval = null;
                }
            }

            if (nextBtn) {
                nextBtn.addEventListener('click', function(e) {
                    e.preventDefault();
                    stopTicker();
                    slideNext();
                    startTicker();
                });
            }

            if (prevBtn) {
                prevBtn.addEventListener('click', function(e) {
                    e.preventDefault();
                    stopTicker();
                    slidePrev();
                    startTicker();
                });
            }

            tickerList.addEventListener('mouseenter', stopTicker);
            tickerList.addEventListener('mouseleave', startTicker);

            startTicker();
        }

        // 2. Hero Slider Carousel
        const sliderDots = document.querySelectorAll('.slider-dot');
        const sliderSlides = document.querySelectorAll('.hero-slide');
        
        if (sliderSlides.length > 1 && sliderDots.length > 0) {
            let activeSlideIndex = 0;
            let slideInterval = null;

            function showSlide(index) {
                sliderSlides.forEach((slide, idx) => {
                    slide.style.display = (idx === index) ? 'block' : 'none';
                });

                sliderDots.forEach((dot, idx) => {
                    if (idx === index) {
                        dot.classList.add('active');
                    } else {
                        dot.classList.remove('active');
                    }
                });
            }

            function nextSlide() {
                activeSlideIndex = (activeSlideIndex + 1) % sliderSlides.length;
                showSlide(activeSlideIndex);
            }

            function startSlider() {
                if (!slideInterval) {
                    slideInterval = setInterval(nextSlide, 5000);
                }
            }

            function stopSlider() {
                if (slideInterval) {
                    clearInterval(slideInterval);
                    slideInterval = null;
                }
            }

            sliderDots.forEach((dot, index) => {
                dot.addEventListener('click', function() {
                    stopSlider();
                    activeSlideIndex = index;
                    showSlide(activeSlideIndex);
                    startSlider();
                });
            });

            showSlide(0);
            startSlider();
        } else if (sliderSlides.length === 1) {
            sliderSlides[0].style.display = 'block';
        }

        // 3. Category Tabs Filter (Homepage Filter)
        const tabButtons = document.querySelectorAll('.cat-tab-btn');
        const gridCards = document.querySelectorAll('.grid-news-card');

        if (tabButtons.length > 0 && gridCards.length > 0) {
            tabButtons.forEach(button => {
                button.addEventListener('click', function() {
                    tabButtons.forEach(btn => btn.classList.remove('active'));
                    this.classList.add('active');

                    const filterCategory = this.getAttribute('data-category');

                    gridCards.forEach(card => {
                        const cardCats = card.getAttribute('data-cats') ? card.getAttribute('data-cats').split(',') : [];
                        if (filterCategory === 'all' || cardCats.includes(filterCategory)) {
                            card.style.display = 'flex';
                            card.style.opacity = '0';
                            card.style.transform = 'translateY(10px)';
                            setTimeout(() => {
                                card.style.transition = 'opacity 0.4s ease, transform 0.4s ease';
                                card.style.opacity = '1';
                                card.style.transform = 'translateY(0)';
                            }, 50);
                        } else {
                            card.style.display = 'none';
                        }
                    });
                });
            });
        }

        // 4. Mobile Menu Toggle
        const menuToggle = document.querySelector('.menu-toggle');
        const primaryMenu = document.getElementById('primary-menu');
        
        if (menuToggle && primaryMenu) {
            menuToggle.addEventListener('click', function(e) {
                e.preventDefault();
                const expanded = this.getAttribute('aria-expanded') === 'true';
                this.setAttribute('aria-expanded', !expanded);
                this.classList.toggle('active');
                primaryMenu.classList.toggle('active');
            });
        }

        // 5. Dark Mode Toggle
        const darkModeToggle = document.getElementById('darkModeToggle');
        if (darkModeToggle) {
            const savedDarkMode = localStorage.getItem('bhaiyyantop_dark_mode');
            const icon = darkModeToggle.querySelector('i');
            
            if (savedDarkMode === 'true') {
                document.body.classList.add('dark-mode');
                if (icon) icon.className = 'fa fa-sun';
            }

            darkModeToggle.addEventListener('click', function(e) {
                e.preventDefault();
                const isDarkMode = document.body.classList.toggle('dark-mode');
                localStorage.setItem('bhaiyyantop_dark_mode', isDarkMode);
                
                if (icon) {
                    icon.className = isDarkMode ? 'fa fa-sun' : 'fa fa-moon';
                }
            });
        }

        // 6. Interactive Search Trigger & Modal
        const searchBtn = document.getElementById('searchTriggerBtn');
        const searchModal = document.getElementById('searchOverlayModal');
        const closeSearchBtn = document.getElementById('closeSearchBtn');

        if (searchBtn && searchModal) {
            searchBtn.addEventListener('click', function(e) {
                e.preventDefault();
                searchModal.style.display = 'flex';
                const inputField = searchModal.querySelector('input[type="search"]');
                if (inputField) inputField.focus();
            });
        }

        if (closeSearchBtn && searchModal) {
            closeSearchBtn.addEventListener('click', function() {
                searchModal.style.display = 'none';
            });
        }

        if (searchModal) {
            searchModal.addEventListener('click', function(e) {
                if (e.target === searchModal) {
                    searchModal.style.display = 'none';
                }
            });
        }

        // 7. Interactive Subscribe Modal
        const subBtn = document.getElementById('subscribeBtn');
        if (subBtn) {
            subBtn.addEventListener('click', function(e) {
                e.preventDefault();
                let subBox = document.getElementById('headerSubscribeOverlay');
                if (!subBox) {
                    subBox = document.createElement('div');
                    subBox.id = 'headerSubscribeOverlay';
                    subBox.innerHTML = `
                        <div style="position:fixed; inset:0; background:rgba(0,0,0,0.7); backdrop-filter:blur(5px); z-index:9999; display:flex; align-items:center; justify-content:center;">
                            <div style="background:#ffffff; padding:35px; border-radius:12px; max-width:450px; width:90%; text-align:center; box-shadow:0 15px 30px rgba(0,0,0,0.3); position:relative;">
                                <button id="closeSubBtn" style="position:absolute; top:12px; right:16px; background:none; border:none; font-size:24px; cursor:pointer; color:#777;">&times;</button>
                                <div style="width:60px; height:60px; background:#e91e63; color:#fff; border-radius:50%; display:flex; align-items:center; justify-content:center; margin:0 auto 15px; font-size:28px;"><i class="fa fa-envelope"></i></div>
                                <h3 style="margin-bottom:10px; font-family:'Noto Sans Devanagari', sans-serif; color:#1a1a1a;">भैय्यान्टॉप न्यूज़लेटर सब्सक्राइब करें</h3>
                                <p style="font-size:14px; color:#666; margin-bottom:20px;">देश-दुनिया की ताज़ा खबरें सीधे अपने इनबॉक्स में पाएं!</p>
                                <form onsubmit="event.preventDefault(); alert('धन्यवाद! आपका सब्सक्रिप्शन सफल रहा।'); this.closest('#headerSubscribeOverlay').remove();" style="display:flex; flex-direction:column; gap:12px;">
                                    <input type="email" placeholder="अपना ईमेल एड्रेस दर्ज करें..." style="padding:12px 16px; border:1px solid #ccc; border-radius:6px; font-size:14px;" required>
                                    <button type="submit" style="background:#e91e63; color:#fff; border:none; padding:12px; border-radius:6px; font-weight:800; font-size:15px; cursor:pointer;">अभी सब्सक्राइब करें</button>
                                </form>
                            </div>
                        </div>
                    `;
                    document.body.appendChild(subBox);
                    document.getElementById('closeSubBtn').addEventListener('click', () => subBox.remove());
                    subBox.addEventListener('click', (ev) => {
                        if (ev.target === subBox) subBox.remove();
                    });
                }
            });
        }
    });
    <?php
    return ob_get_clean();
}

/**
 * Returns inline JavaScript string for Single Post reading progress and share actions.
 *
 * @return string JavaScript code string.
 */
function bhaiyyantop_get_single_inline_script() {
    ob_start();
    ?>
    document.addEventListener('DOMContentLoaded', function() {
        'use strict';

        // 1. Reading Progress Bar Indicator
        const progressBar = document.getElementById('readingProgressBar');
        const articleContainer = document.querySelector('.single-post-content');

        if (progressBar && articleContainer) {
            window.addEventListener('scroll', function() {
                const articleTop = articleContainer.offsetTop;
                const articleHeight = articleContainer.offsetHeight;
                const windowHeight = window.innerHeight;
                const scrollTop = window.scrollY;

                if (scrollTop >= articleTop) {
                    const totalScrollable = articleHeight - windowHeight + articleTop;
                    let progress = ((scrollTop - articleTop) / totalScrollable) * 100;
                    progress = Math.min(100, Math.max(0, progress));
                    progressBar.style.width = progress + '%';
                } else {
                    progressBar.style.width = '0%';
                }
            });
        }

        // 2. Copy Share Link Handler
        const copyBtn = document.getElementById('copyShareLinkBtn');
        if (copyBtn) {
            copyBtn.addEventListener('click', function() {
                const linkToCopy = this.getAttribute('data-link') || window.location.href;
                navigator.clipboard.writeText(linkToCopy).then(function() {
                    const originalIcon = copyBtn.innerHTML;
                    copyBtn.innerHTML = '<i class="fa fa-check"></i>';
                    alert('लिंक क्लिपबोर्ड पर कॉपी हो गया!');
                    setTimeout(function() {
                        copyBtn.innerHTML = originalIcon;
                    }, 2000);
                }).catch(function(err) {
                    console.error('Copy link failed: ', err);
                });
            });
        }

        // 3. Back To Top Floating Button
        let backToTopBtn = document.getElementById('backToTopBtn');
        if (!backToTopBtn) {
            backToTopBtn = document.createElement('button');
            backToTopBtn.id = 'backToTopBtn';
            backToTopBtn.setAttribute('aria-label', 'Back to top');
            backToTopBtn.innerHTML = '<i class="fa fa-arrow-up"></i>';
            document.body.appendChild(backToTopBtn);
        }

        window.addEventListener('scroll', function() {
            if (window.scrollY > 400) {
                backToTopBtn.classList.add('visible');
            } else {
                backToTopBtn.classList.remove('visible');
            }
        });

        backToTopBtn.addEventListener('click', function() {
            window.scrollTo({
                top: 0,
                behavior: 'smooth'
            });
        });
    });
    <?php
    return ob_get_clean();
}

/**
 * Output dynamic scripts into footer via PHP hook.
 */
function bhaiyyantop_print_footer_scripts() {
    echo '<script type="text/javascript">' . bhaiyyantop_get_theme_inline_script() . '</script>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
    if ( is_single() ) {
        echo '<script type="text/javascript">' . bhaiyyantop_get_single_inline_script() . '</script>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
    }
}
add_action( 'wp_footer', 'bhaiyyantop_print_footer_scripts', 99 );
